enum SFW_FILE {
  UNIVERSITY1 = 1,
  UNIVERSITY2,
  UNIVERSITY3,
  UNIVERSITY4,
  COLLEGE_CAMPUS1,
  COLLEGE_CAMPUS2,
  COLLEGE_CAMPUS3,
  COLLEGE_CAMPUS4,
  DEPARTMENT1,
  DEPARTMENT2,
  DEPARTMENT3,
  DEPARTMENT4,
  SPORTS_SOCIO1,
  SPORTS_SOCIO2,
  SPORTS_SOCIO3,
  MEMBER_ADHOC1,
  MEMBER_ADHOC2,
  MEMBER_ADHOC3,
  ACADEMIC
}

export { SFW_FILE };
