export type StrategicFunctionType = {
  designationUniversityLevel?: string[];
  approvedUniversityDesignationFile?: File;
  approvedUniversityDesignationFilePath?: string;
  designationCollegeCampusLevel?: string[];
  approvedCollegeCampusDesignationFile?: File;
  approvedCollegeCampusDesignationFilePath?: string;
  designationDepartmentLevel?: string[];
  approvedDepartmentDesignationFile?: File;
  approvedDepartmentDesignationFilePath?: string;
  designationAsSportTrainorAcademic?: string;
  coachAdviserCertificateFile?: File;
  coachAdviserCertificateFilePath?: string;
  designationAsMemberOfAdhoc?: string;
  approvedDesignationFile?: File;
  approvedDesignationFilePath?: string;
  totalOfAcademicAdvisees?: string;
  listOfAdviseesFile?: File;
  listOfAdviseesFilePath?: string;
};
