import {
  Designation,
  DesignationWithPoints
} from "../screens/FacultyWorkload/StrategicFunction/StrategicFunction";
import { PointsAndRemarks } from "../screens/WorkloadReview/RemarksWorkload";

export type StrategicFunctionType = {
  id?: string;
  designationUniversityLevel?: string[];
  designationUniversityLevelFiles?: File[];
  designationUniversityLevelFilesFilenames?: string[];
  approvedUniversityDesignationFilePath?: string[];
  approvedUniversityDesignationFilenames?: string[];
  designationCollegeCampusLevel?: string[];
  designationCollegeCampusLevelFiles?: File[];
  approvedCollegeCampusDesignationFilePath?: string[];
  approvedCollegeCampusDesignationFilenames?: string[];
  designationDepartmentLevel?: string[];
  designationDepartmentLevelFiles?: File[];
  approvedDepartmentDesignationFilePath?: string[];
  approvedDepartmentDesignationFilenames?: string[];
  designationAsSportTrainorAcademic?: string;
  designationAsSportTrainorAcademicFile?: File;
  designationAsSportTrainorAcademicFilename?: string;
  designationAsSportTrainorAcademicPoints?: number;
  designationAsSportTrainorAcademicFilePath?: string;
  designationAsSportTrainorAcademic1?: string;
  designationAsSportTrainorAcademicFile1?: File;
  designationAsSportTrainorAcademicFilename1?: string;
  designationAsSportTrainorAcademicPoints1?: number;
  designationAsSportTrainorAcademicFilePath1?: string;
  designationAsSportTrainorAcademic2?: string;
  designationAsSportTrainorAcademicFile2?: File;
  designationAsSportTrainorAcademicFilename2?: string;
  designationAsSportTrainorAcademicPoints2?: number;
  designationAsSportTrainorAcademicFilePath2?: string;
  designationAsMemberOfAdhoc?: string;
  designationAsMemberOfAdhocFile?: File;
  designationAsMemberOfAdhocFilename?: string;
  designationAsMemberOfAdhocPoints?: number;
  designationAsMemberOfAdhocFilePath?: string;
  memberAdhocFilePath?: string;
  designationAsMemberOfAdhoc1?: string;
  designationAsMemberOfAdhocFile1?: File;
  designationAsMemberOfAdhocFilename1?: string;
  designationAsMemberOfAdhocPoints1?: number;
  designationAsMemberOfAdhocFilePath1?: string;
  memberAdhocFilePath1?: string;
  designationAsMemberOfAdhoc2?: string;
  designationAsMemberOfAdhocFile2?: File;
  designationAsMemberOfAdhocFilename2?: string;
  designationAsMemberOfAdhocPoints2?: number;
  designationAsMemberOfAdhocFilePath2?: string;
  memberAdhocFilePath2?: string;
  academicAdvisees?: string;
  academicAdviseesFile?: File;
  academicAdviseesFilename?: string;
  academicAdviseesPoints?: number;
  academicAdviseesFilePath?: string;
  sfwPoints?: number;
  remarks?: PointsAndRemarks;
  isSubmitted?: boolean;
};
